FROM rust:latest AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y \
  libgtk-3-dev \
  libwebkit2gtk-4.1-dev \
  libjavascriptcoregtk-4.1-dev \
  librsvg2-dev \
  libsoup2.4-dev \
  libglib2.0-dev \
  patchelf \
  libayatana-appindicator3-dev

# Copy entire repo
COPY . .

# Build the release binary
RUN cargo build --manifest-path src-tauri/Cargo.toml --release && \
  cp src-tauri/target/release/diskraptor /diskraptor

FROM scratch
COPY --from=builder /diskraptor /diskraptor
