(function () {
  "use strict";
  window.app = window.app || {};

  window.app.initExport = function (refs) {
    const state = window.app.state;
    const { scanPath, btnExport, loader } = refs;

    // Export button handler (CSV / JSON / HTML)
    btnExport.addEventListener("click", async function () {
      try {
        const choice = await exportDialog();
        if (!choice) return;
        const fmt = choice.format;
        let stats = state.currentStats || {};
        const scanPathVal = scanPath.value || "";
        const nodes = loader.allNodes || [];
        const topN = choice.topN > 0 ? Math.min(choice.topN, nodes.length) : nodes.length;

        if (fmt === "CSV") {
          let csv = "Path,Size,File Count,Dir Count,Type\n";
          for (let ni = 0; ni < topN; ni++) {
            const n = nodes[ni];
            if (!n) continue;
            let fullPath = scanPathVal;
            if (n.name && n.name !== scanPathVal) {
              const parts = [n.name];
              let p = n.parent;
              let safety = 0;
              while (
                p !== 4294967295 &&
                p !== undefined &&
                safety < 100
              ) {
                const parent = nodes[p];
                if (parent && parent.name)
                  parts.unshift(parent.name);
                p = parent ? parent.parent : 4294967295;
                safety++;
              }
              fullPath = scanPathVal + "/" + parts.join("/");
            }
            const esc = function (v) {
              return '"' + String(v).replace(/"/g, '""') + '"';
            };
            csv +=
              esc(fullPath) +
              "," +
              (n.size || 0) +
              "," +
              (n.file_count || 0) +
              "," +
              (n.dir_count || 0) +
              "," +
              (n.node_type === 1 ? "File" : "Directory") +
              "\n";
          }
          downloadBlob(new Blob([csv], { type: "text/csv" }), "diskraptor-export-" + Date.now() + ".csv");
        } else if (fmt === "JSON") {
          // Export all nodes (not just topN) so the file is complete.
          const allNodes = nodes.slice(0, topN).map(function (n, i) {
            return { index: i, name: n && n.name, size: n && n.size, file_count: n && n.file_count, dir_count: n && n.dir_count, type: n && n.node_type === 1 ? "File" : "Directory" };
          });
          const json = JSON.stringify(
            {
              export_time: new Date().toISOString(),
              scan_path: scanPathVal,
              stats: stats,
              nodes: allNodes,
            },
            null,
            2,
          );
          downloadBlob(new Blob([json], { type: "application/json" }), "diskraptor-export-" + Date.now() + ".json");
        } else {
          // HTML report
          let fileRows = "";
          for (let ni = 0; ni < topN && ni < 500; ni++) {
            const hn = nodes[ni];
            if (!hn) continue;
            fileRows +=
              "<tr><td>" +
              escHtml(hn.name || "") +
              "</td><td>" +
              (hn.size || 0) +
              "</td></tr>\n";
          }
          let chartData = "";
          try {
            const svg = document.querySelector("#diagram-container canvas");
            chartData = svg ? svg.toDataURL() : "";
          } catch (e) {}
          const htmlReport =
            '<!DOCTYPE html><html><head><meta charset="utf-8"><title>DiskRaptor Report</title><style>body{font-family:sans-serif;margin:20px;color:#333}h1{color:#2ea043}table{border-collapse:collapse;width:100%}th,td{padding:6px 10px;text-align:left;border-bottom:1px solid #eee}th{background:#f5f5f5}</style></head><body>' +
            "<h1>\uD83E\uDD96 DiskRaptor Report</h1>" +
            "<p>Path: " + escHtml(scanPathVal) + "</p>" +
            "<p>Files: " +
            (stats.total_files || 0) +
            " | Dirs: " +
            (stats.total_dirs || 0) +
            " | Size: " +
            (stats.size_human || "0 B") +
            "</p>" +
            (chartData ? '<img src="' + chartData + '" style="max-width:600px;">' : "") +
            "<h2>Files</h2><table><tr><th>Name</th><th>Size</th></tr>" +
            fileRows +
            "</table>" +
            '<p style="color:#999;font-size:11px;margin-top:20px;">Generated by DiskRaptor</p></body></html>';
          downloadBlob(new Blob([htmlReport], { type: "text/html" }), "diskraptor-report-" + Date.now() + ".html");
        }
        document.querySelector(".status-bar").textContent = (
          window.__ || function (s) { return s; }
        )("status.exported").replace("{fmt}", fmt);
      } catch (err) {
        console.error("Export failed:", err);
        window.showToast("Export failed: " + err, "error");
      }
    });

    function downloadBlob(blob, name) {
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = name;
      a.click();
      URL.revokeObjectURL(url);
    }

    function escHtml(s) {
      return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }

    function exportDialog() {
      return new Promise(function (resolve) {
        const ov = document.createElement("div");
        ov.style.cssText =
          "position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,0.5);display:flex;align-items:center;justify-content:center;";
        const card = document.createElement("div");
        card.style.cssText =
          "background:var(--bg-secondary);border:1px solid var(--border);border-radius:12px;max-width:360px;width:90%;overflow:hidden;box-shadow:0 16px 48px rgba(0,0,0,0.4);";
        card.innerHTML =
          '<div style="padding:12px 16px;border-bottom:1px solid var(--border);font-size:14px;font-weight:600;">\uD83D\uDCC4 Export</div>' +
          '<div style="padding:16px;display:flex;flex-direction:column;gap:12px;">' +
          '<label style="font-size:12px;color:var(--text-secondary);">Format</label>' +
          '<select id="exp-format" style="padding:7px 10px;font-size:13px;border:1px solid var(--border);border-radius:6px;background:var(--bg-primary);color:var(--text-primary);">' +
          '<option value="CSV">CSV</option>' +
          '<option value="JSON">JSON</option>' +
          '<option value="HTML">HTML Report</option>' +
          "</select>" +
          '<label style="font-size:12px;color:var(--text-secondary);">Rows (0 = all)</label>' +
          '<input id="exp-rows" type="number" min="0" value="0" style="padding:7px 10px;font-size:13px;border:1px solid var(--border);border-radius:6px;background:var(--bg-primary);color:var(--text-primary);" />' +
          "</div>" +
          '<div style="padding:10px 16px;border-top:1px solid var(--border);display:flex;justify-content:flex-end;gap:8px;">' +
          '<button id="exp-cancel" style="padding:6px 14px;font-size:12px;border:1px solid var(--border);border-radius:6px;background:var(--bg-tertiary);color:var(--text-primary);cursor:pointer;">Cancel</button>' +
          '<button id="exp-ok" style="padding:6px 16px;font-size:12px;border:none;border-radius:6px;background:linear-gradient(135deg,#238636,#2ea043);color:#fff;cursor:pointer;font-weight:600;">Export</button>' +
          "</div>";
        ov.appendChild(card);
        document.body.appendChild(ov);
        function close() { if (ov.parentNode) ov.parentNode.removeChild(ov); }
        function submit() {
          const format = card.querySelector("#exp-format").value;
          const rows = parseInt(card.querySelector("#exp-rows").value) || 0;
          close();
          resolve({ format: format, topN: rows });
        }
        card.querySelector("#exp-cancel").onclick = function () { close(); resolve(null); };
        card.querySelector("#exp-ok").onclick = submit;
        ov.onclick = function (e) { if (e.target === ov) { close(); resolve(null); } };
        card.querySelector("#exp-rows").addEventListener("keydown", function (e) { if (e.key === "Enter") submit(); });
      });
    }
  };
})();
