@echo off
set DISKraptor_CDP_PORT=9222
set PATH=C:\Program Files\DiskRaptor\runtime;C:\Program Files\DiskRaptor;%PATH%
echo Starting DiskRaptor...
start /b "" "C:\Program Files\DiskRaptor\DiskRaptor.exe" > C:\temp\dr_stdout.txt 2>C:\temp\dr_stderr.txt
echo Launched, waiting 12 seconds...
ping -n 12 127.0.0.1 >nul
echo Checking port 9222...
netstat -ano | findstr "9222"
echo Checking if process is running...
tasklist /fi "IMAGENAME eq DiskRaptor.exe" 2>nul
echo DONE.
